Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID
sonic-net/sonic-swss pull request #2538
Opened 2022-11-21 05:32 UTC by tapashdas

**What I did**
Updated handling of VRF_VNI mapping and VLAN_VNI mapping for same VNI ID

**Why I did it**
When a VNI (L3 VNI) is mapped to VRF,  corresponding VNI (L2 VNI) to Vlan mapping is not required.
Updated VxLAN Orchagent code to remove Vlan-VNI mapping entry when VRF is mapped to same VNI.
Also Re-add Vlan-VNI mapping entry when VRF-VNI mapping for same VNI is removed.

**How I verified it**

**Details if related**

2022-11-21 05:42 UTC, tapashdas commented
@srj102 @RajeshPukhrajJain  Please review

2022-11-21 05:45 UTC, tapashdas commented
@dgsudharsan Please review

2022-11-21 05:51 UTC, tapashdas commented
@LaveenBrcm Please review

2022-11-21 05:58 UTC, tapashdas commented
@hasan-brcm Please review

2022-11-21 07:17 UTC, srj102 commented
Please update the pytest as well.

2022-11-23 23:02 UTC, dgsudharsan requested changes
Please add UT.
There is a flow where VRF - VNI gets mapped first and then VLAN - VNI map arrives later. This PR doesn't handle it. Please handle that flow.

2022-11-29 15:37 UTC, tapashdas commented
> 

Done

2022-12-01 05:26 UTC, dgsudharsan commented
> > 
> 
> Done

Thanks. The existing UT fail due to new logic. Can you please update the UT?

2022-12-06 03:31 UTC, tapashdas commented
Will do. Occupied with other work items.

2022-12-09 00:28 UTC, dgsudharsan commented
> Will do. Occupied with other work items. Updated VRF-VNI test case. They are passing now. Current failures are from the newly added test case you added.

Understood. Can you please provide an ETA for addressing them?

2022-12-15 04:14 UTC, dgsudharsan approved these changes

2022-12-16 01:03 UTC, tapashdas commented
/azpw run

2022-12-17 03:01 UTC, tapashdas commented
‘/azpw run’

2022-12-17 03:08 UTC, tapashdas commented
/azpw run

2022-12-17 03:08 UTC, mssonicbld commented
/AzurePipelines run

2022-12-19 04:26 UTC, tapashdas commented
/azpw run

2022-12-19 04:26 UTC, mssonicbld commented
/AzurePipelines run

2022-12-19 18:10 UTC, prsunny commented
/azp run

2022-12-21 03:28 UTC, tapashdas commented
Please merge the changes.

2022-12-22 18:38 UTC, prsunny approved these changes

2022-12-22 18:38 UTC, prsunny commented on orchagent/vxlanorch.cpp
> +        if(entry.isL2Vni)
please have space after` if `.

2022-12-22 18:38 UTC, merged

2022-12-28 05:24 UTC, dgsudharsan commented
@tapashdas Can you please raise submodule update?

2023-01-05 03:18 UTC, keboliu commented
@StormLiangMS  would you please help to cherry-pick to the 202211 branch?