[Dual-ToR][ACL] bind LAG to ACL table in order to guarantee rule coverage if lag menber will be added to LAG after binding
sonic-net/sonic-swss pull request #2749
Opened 2023-04-24 14:25 UTC by ayurkiv-nvda

**What I did**
Bind LAG to ACL table in order to guarantee ACL rule coverage if LAG member will be added to LAG after ACL binding

**Why I did it**
After config reload or reboot due to timing, we often see race condition when port are not yet added to LAG, but egress ACL table group already created and port is bound to this group.
It causes that ACL rules are not working on LAG's members that were added after binding.

**How I verified it**
Run test:
`py.test dualtor_io/test_normal_op.py::test_normal_op_upstream[active-standby]`

**Details if related**

2023-04-26 00:15 UTC, prsunny approved these changes
lgtm

2023-04-26 00:16 UTC, prsunny commented
why is the PR to 202205? where is the master PR?

2023-04-26 00:17 UTC, prsunny requested changes
please raise PR to master first.

2023-04-26 00:26 UTC, bingwang-ms commented
@ayurkiv-nvda I Rember the original PR is in your personal fork. Can you please raise a PR to master first?

2023-04-27 20:43 UTC, ayurkiv-nvda commented
> please raise PR to master first.

Please take a look at https://github.com/sonic-net/sonic-swss/pull/2754

2023-05-10 17:59 UTC, liat-grozovik commented
/azp run Azure.sonic-swss

2023-05-16 15:36 UTC, ayurkiv-nvda commented
/azpw run Azure.sonic-swss

2023-05-16 15:36 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss

2023-05-16 15:37 UTC, ayurkiv-nvda commented
/azpw run Azure.sonic-swss (Test vstest)

2023-05-16 15:38 UTC, mssonicbld commented
/AzurePipelines run Azure.sonic-swss (Test vstest)

2023-05-28 11:59 UTC, ayurkiv-nvda commented
PR checks should pass after merging https://github.com/sonic-net/sonic-swss/pull/2767 to 202205

2023-06-04 14:03 UTC, ayurkiv-nvda commented
@prsunny  can you please re-approve this PR again?
PR checks failure fixed

@yxieca I think we can merge it to 202205

2023-06-14 22:03 UTC, prsunny approved these changes

2023-06-14 22:03 UTC, merged