[orchagent]: admin-disable port before setPortSerdesAttribute()
sonic-net/sonic-swss pull request #2831
Opened 2023-06-23 03:29 UTC by amnsinghal

**What I did**
Admin-disable port before applying media-based NPU serdes attributes from [media_settings.json](https://github.com/sonic-net/SONiC/blob/master/doc/media-settings/Media-based-Port-settings.md).

**Why I did it**
This fix is needed along with xcvrd changes [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377).
Maintain deterministic behavior of [interface bring-up](https://github.com/sonic-net/SONiC/blob/master/doc/sfp-cmis/Interface-Link-bring-up-sequence.md), by toggling host_tx_ready flag, which will trigger CMIS reinit for the module once NPU serdes params have been applied.

**How I verified it**
Validated media_settings being notified and applied on Cisco 8111 with subject changes combined with diffs from [#360](https://github.com/sonic-net/sonic-platform-daemons/pull/360), [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377) and [#15453](https://github.com/sonic-net/sonic-buildimage/pull/15453).
Will update final results once [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377) is frozen.

**Details if related**
Proposal for xcvrd changes: [#356](https://github.com/sonic-net/sonic-platform-daemons/issues/356)

2023-06-23 03:30 UTC, amnsinghal commented
@prgeor @mihirpat1 for your perusal.

2023-06-25 11:10 UTC, eddyk-nvidia approved these changes
Looks OK to me

2023-06-26 02:16 UTC, Junchao-Mellanox approved these changes

2023-06-26 14:20 UTC, dgsudharsan approved these changes

2023-06-27 19:59 UTC, prgeor commented
@amnsinghal waiting for your UT test: Try this change in master without any other in-flight changes from Mihir's

2023-07-07 01:44 UTC, prgeor commented
@amnsinghal @mihirpat1 we are seeing Xcvrd is missing the event host_tx_ready=False. Xcvrd is busy doing something else while OA sets the host_tx_ready = False and when finally OA sets the host_tx_ready=True, Xcvrd do get the notification but the filtering logic filters this event. Need to see a better way to notify change of media setting to Xcvrd.

2023-07-10 18:46 UTC, amnsinghal commented
> @amnsinghal waiting for your UT test: Try this change in master without any other in-flight changes from Mihir's

@prgeor Here is a summary of UT results without Mihir's diff:
1. **Reboot, config reload**: All dockers/processes start clean, xcvrd starts CMIS FSM, notifies NPU media_settings to OA/syncd/SAI-SDK, link comes up as expected.
2. **xcvrd crash, xcvrd graceful restart**: xcvrd renotifies media_settings, causing link-flap, this should be taken care by [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377).
3. **syncd process crash, syncd docker restart**: xcvrd did not re-notify media_settings, nor did module DP reinit, this should be taken care by [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377). Link went down (due to NPU reset) and came up with default NPU params.
4. **syncd process graceful restart**: xcvrd did not re-notify media_settings, nor did module DP reinit, this should be taken care by [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377). Link went down (due to NPU reset) and came up with media-based NPU params from ASIC-DB.
5. **OA process crash**: xcvrd did not re-notify media_settings, nor did module DP reinit, this should be taken care by [#377](https://github.com/sonic-net/sonic-platform-daemons/pull/377). Link went down (due to NPU reset) and came up with default NPU params.

2023-07-18 20:51 UTC, amnsinghal commented
@prgeor As discussed today, can you pls approve and merge this fix, if no further comments. Thanks.

2023-07-25 05:12 UTC, prgeor commented on orchagent/portsorch.cpp
> +                            SWSS_LOG_NOTICE("Set port %s preemphasis is success", p.m_alias.c_str());
```suggestion
                            SWSS_LOG_NOTICE("Set port %s SI settings is successful", p.m_alias.c_str());
```

2023-07-25 05:13 UTC, prgeor commented on orchagent/portsorch.cpp
> +                            SWSS_LOG_ERROR("Failed to set port %s pre-emphasis", p.m_alias.c_str());
```suggestion
                            SWSS_LOG_ERROR("Failed to set port %s SI settings", p.m_alias.c_str());
```

2023-07-25 05:13 UTC, prgeor approved these changes
@amnsinghal approved with minor comments

2023-07-25 19:40 UTC, amnsinghal commented
/AzurePipelines run

2023-07-25 21:10 UTC, prgeor commented
@prsunny please help approve and merge.

2023-07-25 21:11 UTC, prgeor commented
@amnsinghal re-submitted the test pipeline

2023-07-25 21:22 UTC, amnsinghal commented
> @amnsinghal re-submitted the test pipeline

Thanks @prgeor

2023-07-26 00:18 UTC, amnsinghal commented
@prgeor @prsunny Can you pls rerun Azure Pipeline, prev rerun failed in early build stage, apparently due to env/pipeline issue: https://dev.azure.com/mssonic/build/_build/results?buildId=323644&view=results. This changeset had passed all sanities yesterday. Thanks.

2023-07-28 05:56 UTC, kevinskwang commented
/azp run

2023-07-28 14:28 UTC, lguohan commented
test are failing, also new code needs to add new unit test code.

2023-07-28 14:29 UTC, lguohan requested changes
test are failing, also new code needs to add new unit test code.

2023-07-28 14:30 UTC, lguohan commented
new code path must be protected by new unit test code, adding new logics without new code unit test is not a good practice. @prsunny

2023-07-28 14:58 UTC, amnsinghal commented
> test are failing, also new code needs to add new unit test code.

@lguohan All tests had passed  2 days back before [Update syslog in orchagent/portsorch.cpp ](https://github.com/sonic-net/sonic-swss/pull/2831/commits/a5b94f3850f1c08ab42c9814eec19ab3768c1605), which was just a syslog rephrase, no functional change.

2023-07-28 15:02 UTC, amnsinghal commented
> new code path must be protected by new unit test code, adding new logics without new code unit test is not a good practice. @prsunny

@lguohan This is existing code flow with only addition of admin-disable before applying NPU serdes attributes.

2023-08-22 23:40 UTC, prsunny commented
@amnsinghal , can you please add unit test for coverage of this change?

2023-08-23 19:19 UTC, amnsinghal commented
> @amnsinghal , can you please add unit test for coverage of this change?

@prsunny @lguohan Added UT in mock_tests/portsorch_ut.cpp, kindly review and approve.

2023-08-24 22:32 UTC, prsunny approved these changes

2023-08-24 22:59 UTC, merged

2023-08-24 23:02 UTC, amnsinghal commented
Thanks @prgeor @prsunny @lguohan!
Can you pls request cherry-pick to 202205 and/or 202305.

2023-08-29 17:46 UTC, mihirpat1 commented
@StormLiangMS - Can you please help with cherry-pick to 202305?
ADO - 24988722

2023-09-03 02:43 UTC, StormLiangMS commented
@amnsinghal  there is conflict, could you help to file separate PR for 202305?