[Fdbsyncd] Adding extern_learn flag with fdb entry so Kernel doesn't age out
sonic-net/sonic-swss pull request #2985
Opened 2023-12-07 19:25 UTC by kishorekunal01

- What I did
    extern_learn flag is added while programming the fdb entry into the Kernel. This will make sure that kernel doesn't age out the fdb entry. (#15004)

- How I did it
    A flag extern_learn will be passed while programing the fdb entry. (#15004)

- How to verify it
    Tested MAC add/del to the Kernel from the local FDB entry. (#15004)

Signed-off-by: kishore.kunal@broadcom.com

2024-03-22 01:31 UTC, dgsudharsan requested changes
Can you please add UT or update existing UT?

2024-03-22 01:34 UTC, kishorekunal01 commented
UT is already part of the fdbsyncd, and it is passing with this change

2024-04-03 00:56 UTC, dgsudharsan approved these changes

2024-04-03 00:57 UTC, dgsudharsan commented
Fix for https://github.com/sonic-net/sonic-buildimage/issues/15004

2024-04-03 23:42 UTC, merged