[orchagent]: VXLAN: Fix oper_status and tunnel encapsulation TTL
sonic-net/sonic-swss pull request #3383
Opened 2024-11-20 14:41 UTC by bradh352

**What I did**

This fixes 2 issues across a range of open tickets building upon patches created by others with modifications as requested by @VladimirKuk.

The first issue this resolves is the status shown for remote vteps which in the fact that it is wrong makes debugging nearly impossible:
```
# show vxlan remotevtep
+------------+------------+-------------------+--------------+
| SIP        | DIP        | Creation Source   | OperStatus   |
+============+============+===================+==============+
| 172.16.0.1 | 172.16.0.2 | EVPN              | oper_down    |
+------------+------------+-------------------+--------------+
Total count : 1
```

The remote VTEP is really up.

Original PR for that is #2080.

Also fixes https://github.com/sonic-net/sonic-buildimage/issues/10004 or at least the error message which hurts debugging.

The next issue is in reachabiity across VXLANs.  This fixes IP/MAC learning via ARP.  The original PR for that is #3216, however it appears it has its origins in
https://github.com/sonic-net/sonic-buildimage/issues/10050 which goes into greater detail about the issue itself.  Also there is talk about it here https://github.com/kamelnetworks/sonic/issues/9 as well as another similar patch here: https://github.com/kamelnetworks/sonic-swss/commit/02ee3e3

**Why I did it**

Fixes #3216
Fixes #2080
Fixes https://github.com/sonic-net/sonic-buildimage/issues/10050
Fixes https://github.com/sonic-net/sonic-buildimage/issues/10004

**How I verified it**

Pulled into my private sonic-swss fork:
https://github.com/bradh352/sonic-swss/commits/bradh352/master

Which is pulled in by my private sonic-buildimage fork:
https://github.com/bradh352/sonic-buildimage/tree/bradh352/master

Which is then automatically built when changes are made.  Then the uploaded asset of sonic-broadcom.bin is installed onto Dell S5248F switches and tested.

Update: also now tested by me on Mellanox/NVidia SN2201

**Details if related**

 Signed-off-by: Brad House (@bradh352)

This should also be backported to 202411, 202405

2024-11-20 22:04 UTC, VladimirKuk commented
Tests do fail from time to time.
At least to me, these tests are unrelated to the change.

2024-11-27 19:25 UTC, lukasstockner commented
Thank you for pushing this forward!
For the record, we've been running these changes in production for ~2 years without issues, so I'd be quite confident that they work as expected.

2024-12-04 17:17 UTC, bradh352 commented
@VladimirKuk I ended up having to sprinkle your suggestion in 2 places to get it fully working.

2024-12-05 06:51 UTC, VladimirKuk approved these changes

2024-12-05 17:29 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> -    sai_uint8_t encap_ttl=0)
that is a static function that only exists in that file and is never called without the encap_ttl argument.  The public functions both set the default value and are optional.  I can of course set to a proper default value there if you'd prefer, its just never used so I didn't see a point.

2024-12-05 17:34 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> -    sai_uint8_t encap_ttl=0)
alternatively we can just go back to default of 0 everywhere to explicitly mean "choose something for me", then check for 0 in this and set it to 64.  Some old revisions did that but @VladimirKuk suggested to change it.  I personally don't care either way, both ways definitively fix the issue at hand.

2024-12-07 11:04 UTC, bradh352 commented
@prsunny how would you like to proceed on this?  I think this is a critical issue since community SONiC doesn't support ARP/ND suppression so things just don't work at all without this.

2024-12-13 14:11 UTC, mssonicbld commented
/azp run

2024-12-13 14:12 UTC, bradh352 commented
@prsunny looks like the internal msconflict is resolved now since pvst was merged to main.  Please review and hopefully merge.  Thanks!

2024-12-16 16:04 UTC, bradh352 commented
rebased on top of current master to get rid of merged stuff that is now upstream

2024-12-17 17:46 UTC, mssonicbld commented
/azp run

2024-12-19 12:49 UTC, bradh352 commented
I can't tell from the output if somehow the test failures are related to this PR.  I'm not familiar enough with the test case output to differentiate expected failures from real ones.

2024-12-20 09:40 UTC, mssonicbld commented
/azp run

2025-01-06 18:46 UTC, mssonicbld commented
/azp run

2025-01-07 01:58 UTC, mssonicbld commented
/azp run

2025-01-07 02:00 UTC, mssonicbld commented
/azp run

2025-01-07 09:50 UTC, bradh352 commented
@prsunny figured out the test case failure and corrected it, it was due to specifically checking tunnel attributes and we added 2 new ones.

2025-01-09 13:29 UTC, bradh352 commented
@abdosi, @judyjoseph, @srj102 any review comments?  This is a pretty large blocker for VXLAN EVPN

2025-01-10 14:51 UTC, srj102 requested changes

2025-01-10 14:51 UTC, srj102 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
The current behaviour of this helper function allowed for uniform as well as pipe model with the default being uniform (encap_ttl=0) 
With this change sonic forces tunnels to be in pipe mode which is a step back. 

Hence I would say stick with the current implementation.

2025-01-10 14:55 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
What's the solution here to the issue at hand then?  What we're seeing is ARP across the tunnel no longer works as it gets a TTL of 0 and gets dropped, therefore machines are unable to find eachother across the network.  At least on Broadcom Trident 3.

2025-01-10 15:01 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
or are you saying to try to just set a TTL > 0 in Uniform mode?  So just don't change the mode attribute and see what happens?

2025-01-10 16:42 UTC, srj102 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
Is the ARP TTL issue on Trident3 still seen with the latest SAI versions ?

2025-01-10 16:54 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
as of 3 weeks ago on master anyhow, I haven't tried without this patch since then

2025-01-13 13:10 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
@srj102 how do you want me to proceed here?  I can test anything you want me to test within a few hours, such as setting the TTL be leaving in uniform mode.  That said, I must say with VXLAN EVPN I'm not sure uniform mode make sense anyhow unless I'm missing something.  MPLS it does of course.  I've also seen some vendors indicate they *only* support pipe mode on VXLAN EVPN (https://documentation.extremenetworks.com/slxos/sw/20xx/20.4.3/l2config/GUID-537EC20E-95A2-4CA7-A417-D45D596AD575.shtml)

2025-01-13 16:32 UTC, srj102 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
The default of uniform mode seems to be coming from SAI defaults.

The foll is my suggestion. 
a. Not to change the create_tunnel helper function. 
b. Pass a non default encap_ttl from createTunnelHw()

I am fine with having the default encap ttl mode to be PIPE. 
@prsunny  @dgsudharsan  please comment. 

If this is not acceptable,
 then we might have to have this as PIPE only for BRCM platforms. 
Define a default_encap_ttl and set it to PIPE only for BRCM platforms (platform == BRCM_PLATFORM_SUBSTRING )

2025-01-13 16:46 UTC, mssonicbld commented
/azp run

2025-01-15 15:05 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
@srj102 ping

2025-01-15 17:06 UTC, bradh352 commented on orchagent/vxlanorch.cpp
> +    attr.id = SAI_TUNNEL_ATTR_ENCAP_TTL_MODE;
@srj102 I was really just asking for feedback on the latest changeset, if that's more inline with what you were wanting...

2025-01-22 14:38 UTC, bradh352 commented
@prsunny @dgsudharsan @srj102 any further feedback here?  I'd really like to get this merged.  There are lots of people using this patch already.

2025-01-22 15:50 UTC, srj102 commented
@bradh352 Thanks for the fixes. 

By keeping the create_tunnel helpers default values we are not impacting the other orchs like nvgre/srv6/tunneldecap.
The latest change you made is fine. 

vnetorch also keeps the VXLAN tunnel created in the PIPE mode and hence we should be able to go with PIPE mode for BGP EVPN vxlan tunnels.

2025-01-22 15:55 UTC, bradh352 commented
> @bradh352 Thanks for the fixes.
> 
> By keeping the create_tunnel helpers default values we are not impacting the other orchs like nvgre/srv6/tunneldecap. The latest change you made is fine.
> 
> vnetorch also keeps the VXLAN tunnel created in the PIPE mode and hence we should be able to go with PIPE mode for BGP EVPN vxlan tunnels.

Can you mark it as approved?

Also, I recently acquired a Mellanox Spectrum1 switch (SN2201) for testing and can confirm this patch also works on that ASIC.

2025-01-22 16:28 UTC, mssonicbld commented
/azp run

2025-01-22 16:28 UTC, bradh352 commented on tests/test_vxlan_tunnel.py
>                  )
done

2025-01-23 13:21 UTC, mssonicbld commented
/azp run

2025-01-23 13:21 UTC, bradh352 commented
looks like builds were hanging yesterday ... I rebased my commits on current master to force a rebuild ... hopefully its fixed today.

2025-01-24 13:10 UTC, mssonicbld commented
/azp run

2025-01-24 13:10 UTC, bradh352 commented
just forced a rebuild, tests failed in srv6 tests ... shouldn't be related in any way to my changes

2025-01-25 18:49 UTC, bradh352 commented
only failures in the log are srv6 related, just like the minimal PR in #3482 also failing due to SRV6 tests failing

2025-01-28 18:51 UTC, mssonicbld commented
/azp run

2025-01-29 16:00 UTC, bradh352 commented
@prsunny looks like tests are passing now that the SRv6 fixes got merged yesterday.  Can this be merged now?

2025-01-29 20:58 UTC, merged